### ISSUE TITLE
cumd conversion to HTML is incomplete

### ISSUE THREAD

**Issue by typiconman** [slavonic/cumd#2]
It looks like the conversion from md to HTML is not complete. It does not honor certain MarkDown features, for example `=kinovar=` and `{{text_align=center}}`.

Two sample files are attached. The command I used was:
`cumd --html 01mytar.md 01mytar.html`

Also it appears the HTML file lacks the closing `</html>` tag, surely a bug?

[sample.zip](https://github.com/slavonic/cumd/files/4365770/sample.zip)

**Comment by pgmmpk** [comment]
I pushed out `cumd` version 1.0.1, that addresses the missing closing `</html>` problem.

However, I can not reproduce the reported `=kinovar=` problem.

Please, follow these instructions to diagnose:
1. install the latest `cumd` package, for example: `pip3 install cumd -U`
2. use `-h` flag to `cumd` command to verify the version (to check that you are running the latest script). Expect to see version as part of the output. It must be (a) present (b) have value 1.0.1, see below
```
usage: cumd.py [-h] [--html] input output

Converts CU markdown to HTML (version 1.0.1)
```

Running this command on supplied sample (almost) correctly expanded into html. Alignment hints were not processed though.

Please, confirm that the only problem in the 1.0.1 is the `{{text_align=xxx}}` not being stripped out

**Comment by typiconman** [comment]
Yes, I can confirm that in 1.0.1 the only problem is the `{{text_align=xxx}}` not being stripped out.

Is there a way we can process the `{{text_align=xxx}}`?

**Comment by pgmmpk** [comment]
As of the latest version 1.1.0 (just pushed out), `{{key1=value1,key2=value2}}` are stripped off and moved as an attribute to the enclosing block.

I also adjusted the style of the HTML generator to do the center alignment when `text_align="center"` attribute is set on `<p>`.

Please, confirm it works.

**Comment by typiconman** [comment]
Yes, it works. Thank you!

The only other issue I see now is that the `<bukvitsa>` tag does not seem to be supported in the CSS declaration. I suggest something like this:
```
        bukvitsa {
            font-family: 'Indiction Unicode';
            font-size: 300%;
            float: left;
            color: var(--kinovar);
            margin-top: -0.3em;
            margin-bottom: -0.3em;
        }
```
Except those last two declaration probably need to be done in relative, rather than absolute numbers?

**Comment by pgmmpk** [comment]
Thanks for confirming.

I do not have a readily available `<bukvitsa>` sample, could you please check if this CSS works okay?
```
        bukvitsa {
            font-family: 'Indiction Unicode';
            font-size: 300%;
            float: left;
            color: var(--kinovar);
            margin-top: -0.3rem;
            margin-bottom: -0.3rem;
        }
```
(I only replaced absolute EM units with relative)

**Comment by typiconman** [comment]
There is a `<bukvitsa>` in the file I attached above.
But yes, the CSS works OK.

**Comment by pgmmpk** [comment]
Minor tweaks added, please check. The new suggested CSS is:
```
        bukvitsa {
            display: inline-block;
            height: 3rem;
            padding-right: 0.25rem;
            font-family: 'Indiction Unicode';
            font-size: 300%;
            float: left;
            color: var(--kinovar);
            margin-top: -0.4rem;
        }
```
![image](https://user-images.githubusercontent.com/569458/77339826-c2930a80-6d02-11ea-9085-f4d7251210ea.png)

If you do not see any problem with this, I will add to the default HTML style then

**Comment by typiconman** [comment]
Yes, that looks even better.

**Comment by pgmmpk** [comment]
Version 1.2.0 published, with bukvitsa CSS added!
