### ISSUE TITLE
Add --max_line_width

### ISSUE THREAD

**Issue by typiconman** [slavonic/cumd#6]
Current a (cosmetic?) line break is added by cuxml (what's the default value? 128?). Perhaps this should be set by a --max_line_width parameter, just as with odt2md?

**Comment by typiconman** [comment]
The presence of line breaks appears to break VS Code's coloring mechanism, but is this a bug in VS Code?

But the preview works correctly
![image](https://github.com/user-attachments/assets/ccc7239d-c3fb-44e3-8df2-b3c23133aafa)

@starover77 you may be interested in this discussion.

**Comment by pgmmpk** [comment]
New CLI flag `-m` (`--max-line-len`) added to control line length in generated markdown. Default is 80.

**Comment by typiconman** [comment]
Wonderful, thanks @pgmmpk
